### ISSUE TITLE
pain au chocolat ou chocolatine?

### ISSUE THREAD

**Issue by axelduret** [Realise-Formation-Digital/20.10-Bootstrap-RestaurantProject#4]

**Comment by NorahZatanna** [comment]
Non mais quelle horreur, respecte la pâtisserie bon sang ! (pain au chocolat bien sûr :D)

**Comment by Lahouari-Geneve** [comment]
Pain au chocolat comme Joe Dassin

**Comment by christophermoret** [comment]
Je n'aime pas les éléctions à 2 candidats je vote donc pour Couque au chocolat et Croissant au chocolat!!!! Et en profite pour partager quelques rires: https://www.youtube.com/watch?v=hz5xWgjSUlk&ab_channel=INAHumour
